
import = ["/home/manuel/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.bold_italic]
family = " Roboto Mono"
style = "Bold Italic"
